name: Deploy Chaos Chess

on:
  push:
    branches: ["main"] 

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install and Deploy 🚀
        run: |
          # 1. Configure Git Identity on build runner
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          # 2. Proceed with install and deploy
          npm install
          npm run deploy
